GET http://localhost:3000/units

###

GET http://localhost:3000/units/61fb085671225b6828b49468

###

POST http://localhost:3000/units
Content-Type: application/json

{
    "name": "Marine",
    "race": "Terran",
    "description": "Melee boy",
    "type": "Ground Unit",
    "targets": "Ground, Air",
    "strongAgainst": "Testing",
    "weakAgainst": "Testing"
}

###

DELETE http://localhost:3000/units/61fb0cb7e794da2082102798

###

PATCH http://localhost:3000/units/"61f36c42b952af557a325fdd"
Content-Type: application/json

{
    "description": "test"

}