GET http://localhost:3000/units

###

GET http://localhost:3000/units/61fb085671225b6828b49468

###

POST http://localhost:3000/units
Content-Type: application/json

{
    "name": "Probe",
    "race": "Protoss",
    "type": "Small Ground Unit",
    "description": "Basic worker unit. Can gather resources and warp in Protoss structures.",
    "targets": "Ground",
    "strongAgainst": null,
    "weakAgainst": null
}

###

DELETE http://localhost:3000/units/61fb0cb7e794da2082102798

###

PATCH http://localhost:3000/units/"61f36c42b952af557a325fdd"
Content-Type: application/json

{
    "description": "test"

}